/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.kuznetsov.calendar;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.String;

public class AppTest {
  @Test public void weekDayAfter1024Days(){
    GregorianCalendar calendar = new GregorianCalendar(2020,10,29);
    calendar.addDays(1024);
    String result = calendar.weekDay();
    assertEquals("Saturday", result);
  }

  @Test public void dateFromTheVictoryDay(){
    GregorianCalendar calendar = new GregorianCalendar(2020,10,29);
    calendar.subDate(9,5,1945);
    assertEquals(23,calendar.day());
    assertEquals(5,calendar.month());
    assertEquals(75,calendar.year());
  }
  @Test public void weekDayOfMyBirthday(){
    GregorianCalendar calendar = new GregorianCalendar(2001, 12,15);
    String result = calendar.weekDay();
    assertEquals("Saturday",result);
  }
  @Test public void monthAfter17Weeks(){
    GregorianCalendar calendar = new GregorianCalendar(2020,10,29);
    calendar.addDays(17*7);
    assertEquals(2,calendar.month());
  }
  @Test public void daysToNewYear(){
    GregorianCalendar calendar = new GregorianCalendar(2020,10,29);
    int result = calendar.daysToNewYear();
    assertEquals(63,result);
  }
  @Test public void nextFriday13(){
    GregorianCalendar calendar = new GregorianCalendar(2020,10,29);
    Calendar result = calendar.nextFriday13();
    assertEquals(2020, result.year());
    assertEquals(11,result.month());
    assertEquals(13,result.day());
  }
}
